### ISSUE TITLE
Products block: Add tappable-card utility to parent theme

### ISSUE THREAD

**Issue by douglas-johnson** [thoughtis/cata#117]
### Background

We sometimes use the [pseduo content trick](https://inclusive-components.design/cards/#thepseudocontenttrick) to make it possible to tap / click a whole card component. This was implemented in child themes, but we are using it in the custom blocks available to all child themes. 

The LESS should look like:

```less
/**
 * Tappable Card
 *
 * Use a pseudo element on the selected <a> tag make the whole card a tap target.
 */

.tappable-card {
	position: relative;
}

.tappable-card-anchor::before {
	content: "";
	position: absolute;
	.inset-inline-start(0);
	.inset-block-start(0);
	block-size: 100%;
	inline-size: 100%;
	z-index: 1;
}

.tappable-card-above {
	position: relative;
	z-index: 2;
}
```
