### ISSUE TITLE
Remove our custom block library CSS

### ISSUE THREAD

**Issue by douglas-johnson** [thoughtis/cata#153]
### Background

When the block editor was just for post content, we wrote our own CSS for all the blocks. When the block editor moved into Full Site Editing, there were too many blocks and we added a concatenated CSS file with the core block css for blocks we didn't especially need to customize.

As of WordPress 6.2 I feel the WP core block library's CSS is good enough to use. We have used it on Thought Catalog and removed the uses of the columns block from Creepy Catalog that would conflict with the core block library's CSS.

This will also resolve #125 

### Acceptance Criteria
- [ ] Content looks very similar, if not identical, or can be fixed using editor settings

### Details
- Remove the CSS for wp core blocks and the block modifiers
  - https://github.com/thoughtis/cata/tree/0.8.7/assets/src/less/blocks
- Remove this WordPress gulp task
  - https://github.com/thoughtis/cata/blob/0.8.7/gulpfile.js#L74
- Remove our Core_Columns class, enabling `__experimentalLayout` support
  - https://github.com/thoughtis/cata/blob/0.8.7/includes/blocks/core-columns/class-core-columns.php
- Stop switching the core block library css for our custom compiled one
  - https://github.com/thoughtis/cata/blob/0.8.7/includes/enqueue-assets/class-enqueue-assets.php#L32
- Update our blocking CSS to depend on `wp-block-library` instead of our custom version
  - https://github.com/thoughtis/cata/blob/0.8.7/includes/enqueue-assets/class-enqueue-assets.php#L44
- As noted in a comment in our columns block CSS, child themes have some core block related code in them. That should probably be removed too.
  - https://github.com/thoughtis/cata/blob/master/assets/src/less/blocks/wp-block-columns/layout.less#L11

### Issues I noticed

- The core block library uses `em` units for the gaps in the Post Template block's grid layout. These cause problems with fluid type. We have solved this with more complex math in other scenarios. Long term we could decide to use that came "max column size" math here too, but I think fixing it for the purposes of this issue could be as simple as overriding it to use `rem`
  - https://github.com/WordPress/gutenberg/blob/%40wordpress/block-library%408.10.0/packages/block-library/src/post-template/style.scss
  - I had success locally with the CSS below, but have not tested it with child themes.

```css
.wp-block-post-template.is-flex-container {
	gap:1.25rem;
}
 
@media (min-width:600px){
	.wp-block-post-template.is-flex-container.is-flex-container.columns-2>li{
	  width:calc(50% - .625rem);
	}
	.wp-block-post-template.is-flex-container.is-flex-container.columns-3>li{
	  width:calc(33.33333% - .83333rem);
	}
	.wp-block-post-template.is-flex-container.is-flex-container.columns-4>li{
	  width:calc(25% - .9375rem);
	}
	.wp-block-post-template.is-flex-container.is-flex-container.columns-5>li{
	  width:calc(20% - 1rem);
	}
	.wp-block-post-template.is-flex-container.is-flex-container.columns-6>li{
	  width:calc(16.66667% - 1.04167rem);
	}
}
```
