### ISSUE TITLE
Margin issues related to CSS reset and :where() in WordPress CSS

### ISSUE THREAD

**Issue by douglas-johnson** [thoughtis/cata#177]
In #164 and #165 we tried to deal with the use of the low prioirty selector `:where()` in WordPress's CSS.

However the way we dealt with it caused some other issues.

## Headings

By doing `:where(h1,h2,h3,h4,h5,h6)` in our reset, we are no losing to normalize. So WordPress eventually wins, but any of our custom HTML stuff can get weird. For example the author name H1s on Collective World.

## Images

WordPress produces this inline CSS:
```css
:where(body .is-layout-flow) > * {
  margin-block-start: 1.4444em;
  margin-block-end: 0;
}
```

But it has this in the block-library CSS:
```
:where(figure) {
  margin: 0 0 1em;
}
```

Our reset defeats both:
```css
fieldset, figure, p:empty {
  margin: 0;
}
```

If we wrap our selector in `:where()` the `margin-block-start: 1.4444em;` that we want starts working in block editor contexts. But so does the `margin: 0 0 1em;` which can still be applied outside of block editor contexts elsewhere on the page if not wrapped in a `is-layout-*` class.
